#pragma once
#include "ECSorganizer.hpp"
#include "components.hpp"
#include "constants.hpp"
#include "prefabs.hpp"
#include <random>
#include <glm/gtc/constants.hpp>

const std::vector<std::string> pattern1 = {
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
};
// const std::vector<std::string> pattern1 = {
//     "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
//     "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
//     "XX..XXXOXXXXXXXXXXX..XXXXXXXXXXOXXX..XX",
//     "XX..XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX..XX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "XX..XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX..XX",
//     "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
//     "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
//     "POPOPOPOOPOPOPPOPOPOPOPOOOOPOPPOPPPPOPO",
// };
// };const std::vector<std::string> pattern1 = {
//     "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "XX..XXXOXXXXXXXXXXX..XXXXXXXXXXOXXX..XX",
//     "XX..XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX..XX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "XX..XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX..XX",
//     "XX..XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX..XX",
//     "XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX",
//     "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
// };

const std::vector<std::string> pattern2 = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

const std::vector<std::string> pattern3 = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X",
    "XXXXOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOXXX",
    "XXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXX",
    "XXXX...XXXXXXXXXXXXXXXXXXXXXXXXXX...XXX",
    "XXXXXXXXOXXXXXXXXXXXXXXXXXXXXXXOXXXXXXX",
    "XXX....XXXXXXXXXXXXXXXXXXXXXXXXXX....XX",
    "..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
    "XOXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXO",
    "XXXX..XXXXXXXX..XXXXXXXX..XXXXXXXX..XXX",
};


void buildLayout(ECSOrganizer& ecs, const std::vector<std::string>& pattern, Shader *squareShader);

// for choose scene preview
void buildLayoutPreview(ECSOrganizer& ecs,const GLuint sceneIdx, Shader *squareShader);

void loadScene(ECSOrganizer& ecs, Shader *ballShader, Shader *platformShader, Shader *squareShader, GameScene gameScene, Entity &platform);

void loadMainMenuScene(ECSOrganizer& ecs, Shader *textShader);

void loadGameOverScene(ECSOrganizer &ecs,Shader *textShader);

void loadPausedScene(ECSOrganizer &ecs,Shader *textShader);

void loadWinningScene(ECSOrganizer &ecs,Shader *textShader);

void loadChooseGameSceneScene(ECSOrganizer &ecs,Shader *textShader);

void loadSettingsScene(ECSOrganizer &ecs,Shader *textShader, Shader *squareShader);